# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.vm.define "master", primary: true do |master|
    master.vm.box = "rubicon/centos7-salt"
    master.vm.network "private_network", ip: "10.0.1.10"

    $script = <<-SCRIPT
    yum install -y "http://ftp.acc.umu.se/mirror/fedora/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" git python-pip policycoreutils-python GitPython gcc python-devel gcc-c++
    yum update -y
    pip install --upgrade jinja2
    pip install --upgrade salt
    hostnamectl set-hostname master-vagrant
    echo "127.0.0.1 master-vagrant localhost" > /etc/hosts
    echo master-vagrant > /etc/salt/minion_id
    ln -sf /vagrant/salt/master /etc/salt/master
    ln -sf /vagrant/salt/minion /etc/salt/minion
    systemctl enable salt-master
    systemctl enable salt-minion
    systemctl restart salt-master
    systemctl restart salt-minion
    SCRIPT

    master.vm.provision "shell", inline: $script, privileged: true
  end

  config.vm.define "linux-minion" do |linuxminion|
    linuxminion.vm.box = "rubicon/centos7-salt"
    linuxminion.vm.network "private_network", ip: "10.0.1.20"

    $script = <<-SCRIPT
    yum install -y "http://ftp.acc.umu.se/mirror/fedora/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" git salt-minion python-pip policycoreutils-python
    yum update -y
    pip install --upgrade jinja2
    hostnamectl set-hostname linux-vagrant
    echo -e "127.0.0.1 linux-vagrant localhost\n10.0.1.10 master-vagrant" > /etc/hosts
    echo linux-vagrant > /etc/salt/minion_id
    ln -sf /vagrant/salt/minion /etc/salt/minion
    systemctl enable salt-minion
    systemctl restart salt-minion
    SCRIPT

    linuxminion.vm.provision "shell", inline: $script, privileged: true
  end

end
